apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pipelinesjavascriptdockerdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelinesjavascriptdockerdemo 
    spec:
      containers:
        - name: pipelinesjavascriptdockerdemo 
          image: jsdockerpipelinesdemoacr.azurecr.io/pipelinesjavascriptdockerdemo
          ports:
          - containerPort: 8080